### ISSUE TITLE
Log file breaks when checked

### ISSUE THREAD

**Issue by EvolveAir** [EvolveAir/Karios#1]
While the keylogger is writing characters typed, it also checks if its over 100 characters
The problem is line 265 : `if (File.ReadAllLines(pathToLog).Length <= 100) return CallNextHookEx(_hookId, nCode, wParam, lParam);`

Error is as follows: 
System.IO.IOException
  HResult=0x80070020
  Message=The process cannot access the file 'C:\Users\XXX\2018-02-08DESKTOP-JDTE5K3.txt' because it is being used by another process.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Karios.InterceptKeys.HookCallback(Int32 nCode, IntPtr wParam, IntPtr lParam) in C:\Users\XXX\source\repos\Karios\Karios\Program.cs:line 265

**Comment by EvolveAir** [comment]
Moved to Trello.
